### ISSUE TITLE
Repo missing?

### ISSUE THREAD

**Issue by limex** [dclong/docker-jupyterhub#14]
Hi,
is there a https://github.com/dclong/docker-jupyterhub-ai that you refer to at https://hub.docker.com/r/dclong/jupyterhub-ai/?

**Comment by dclong** [comment]
Hi @limex,
There is a dclong/jupyterhub-ai repo but I marked at private later as I don't think it offer much value compared to the Docker image [dclong/jupyterhub-pytorch](https://github.com/dclong/docker-jupyterhub-pytorch). You can use [dclong/jupyterhub-pytorch](https://github.com/dclong/docker-jupyterhub-pytorch) instead if you are a PyTorch person. 

Sorry about the outdated docs and I will update them.

**Comment by limex** [comment]
Hi,
thanks for the info. I will go for the pytorch repo. BR
