### ISSUE TITLE
Suggestion - Add C++

### ISSUE THREAD

**Issue by RattyDAVE** [dclong/docker-jupyterhub#4]
I have added C++ using the following. 

Feel free to use / add it.

```
apt-get install libtinfo5
mkdir -p ~/pre && cd ~/pre
wget https://root.cern.ch/download/cling/cling_2019-12-08_ubuntu18.tar.bz2
tar jxf cling_2019-12-08_ubuntu18.tar.bz2
cd cling_2019-12-08_ubuntu18
cp -r . /usr/.

cd ~
rm -r pre

cd /usr/share/cling/Jupyter/kernel
pip3 install -e .

jupyter kernelspec install cling-cpp11
jupyter kernelspec install cling-cpp14
jupyter kernelspec install cling-cpp17
jupyter kernelspec install cling-cpp1z
cp /usr/share/cling/Jupyter/kernel/cling.ipynb /workdir
```

**Comment by dclong** [comment]
@RattyDAVE Thank you very much for the suggestion. It does not make sense to add C++ into this Docker image since it is the base for many other Docker images. However, it makes sense to have another docker image named `jupyterhub-cpp` to support C++ kernels. I will build one later.
